export const menuList = [
  {
    searchValue: null,
    createBy: null,
    createTime: '2022-10-19 20:56:47',
    updateBy: null,
    updateTime: null,
    remark: null,
    params: {},
    menuId: 1,
    menuName: '系统管理',
    parentName: null,
    parentId: 0,
    orderNum: 1,
    path: 'system',
    component: null,
    query: '',
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: '',
    icon: 'system',
    children: [
      {
        searchValue: null,
        createBy: null,
        createTime: '2022-10-19 20:56:48',
        updateBy: null,
        updateTime: null,
        remark: null,
        params: {},
        menuId: 100,
        menuName: '用户管理',
        parentName: null,
        parentId: 1,
        orderNum: 1,
        path: 'user',
        component: 'system/user/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:user:list',
        icon: 'user',
        children: [
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1000,
            menuName: '用户查询',
            parentName: null,
            parentId: 100,
            orderNum: 1,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '1',
            perms: 'system:user:query',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1001,
            menuName: '用户新增',
            parentName: null,
            parentId: 100,
            orderNum: 2,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:add',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1002,
            menuName: '用户修改',
            parentName: null,
            parentId: 100,
            orderNum: 3,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:edit',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1003,
            menuName: '用户删除',
            parentName: null,
            parentId: 100,
            orderNum: 4,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:remove',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1004,
            menuName: '用户导出',
            parentName: null,
            parentId: 100,
            orderNum: 5,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:export',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1005,
            menuName: '用户导入',
            parentName: null,
            parentId: 100,
            orderNum: 6,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:import',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1006,
            menuName: '重置密码',
            parentName: null,
            parentId: 100,
            orderNum: 7,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:resetPwd',
            icon: '#',
            children: []
          }
        ]
      },
      {
        searchValue: null,
        createBy: null,
        createTime: '2022-10-19 20:56:48',
        updateBy: null,
        updateTime: null,
        remark: null,
        params: {},
        menuId: 101,
        menuName: '角色管理',
        parentName: null,
        parentId: 1,
        orderNum: 2,
        path: 'role',
        component: 'system/role/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:role:list',
        icon: 'peoples',
        children: []
      }
    ]
  },
  {
    searchValue: null,
    createBy: null,
    createTime: '2022-10-19 20:56:47',
    updateBy: null,
    updateTime: null,
    remark: null,
    params: {},
    menuId: 2,
    menuName: '系统监控',
    parentName: null,
    parentId: 0,
    orderNum: 2,
    path: 'monitor',
    component: null,
    query: '',
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: '',
    icon: 'monitor',
    children: []
  },
  {
    searchValue: null,
    createBy: null,
    createTime: '2022-10-19 20:56:47',
    updateBy: null,
    updateTime: null,
    remark: null,
    params: {},
    menuId: 3,
    menuName: '系统工具',
    parentName: null,
    parentId: 0,
    orderNum: 3,
    path: 'tool',
    component: null,
    query: '',
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: '',
    icon: 'tool',
    children: []
  }
]
export const menuOptions = [
  {
    searchValue: null,
    createBy: null,
    createTime: '2022-10-19 20:56:47',
    updateBy: null,
    updateTime: null,
    remark: null,
    params: {},
    menuId: 1,
    menuName: '系统管理',
    parentName: null,
    parentId: 0,
    orderNum: 1,
    path: 'system',
    component: null,
    query: '',
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: '',
    icon: 'system',
    children: [
      {
        searchValue: null,
        createBy: null,
        createTime: '2022-10-19 20:56:48',
        updateBy: null,
        updateTime: null,
        remark: null,
        params: {},
        menuId: 100,
        menuName: '用户管理',
        parentName: null,
        parentId: 1,
        orderNum: 1,
        path: 'user',
        component: 'system/user/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:user:list',
        icon: 'user',
        children: [
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1000,
            menuName: '用户查询',
            parentName: null,
            parentId: 100,
            orderNum: 1,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:query',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1001,
            menuName: '用户新增',
            parentName: null,
            parentId: 100,
            orderNum: 2,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:add',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1002,
            menuName: '用户修改',
            parentName: null,
            parentId: 100,
            orderNum: 3,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:edit',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1003,
            menuName: '用户删除',
            parentName: null,
            parentId: 100,
            orderNum: 4,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:remove',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1004,
            menuName: '用户导出',
            parentName: null,
            parentId: 100,
            orderNum: 5,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:export',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1005,
            menuName: '用户导入',
            parentName: null,
            parentId: 100,
            orderNum: 6,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:import',
            icon: '#',
            children: []
          },
          {
            searchValue: null,
            createBy: null,
            createTime: '2022-10-19 20:56:48',
            updateBy: null,
            updateTime: null,
            remark: null,
            params: {},
            menuId: 1006,
            menuName: '重置密码',
            parentName: null,
            parentId: 100,
            orderNum: 7,
            path: '',
            component: '',
            query: '',
            isFrame: '1',
            isCache: '0',
            menuType: 'F',
            visible: '0',
            status: '0',
            perms: 'system:user:resetPwd',
            icon: '#',
            children: []
          }
        ]
      },
      {
        searchValue: null,
        createBy: null,
        createTime: '2022-10-19 20:56:48',
        updateBy: null,
        updateTime: null,
        remark: null,
        params: {},
        menuId: 101,
        menuName: '角色管理',
        parentName: null,
        parentId: 1,
        orderNum: 2,
        path: 'role',
        component: 'system/role/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:role:list',
        icon: 'peoples',
        children: []
      }
    ]
  },
  {
    searchValue: null,
    createBy: null,
    createTime: '2022-10-19 20:56:47',
    updateBy: null,
    updateTime: null,
    remark: null,
    params: {},
    menuId: 2,
    menuName: '系统监控',
    parentName: null,
    parentId: 0,
    orderNum: 2,
    path: 'monitor',
    component: null,
    query: '',
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: '',
    icon: 'monitor',
    children: []
  },
  {
    searchValue: null,
    createBy: null,
    createTime: '2022-10-19 20:56:47',
    updateBy: null,
    updateTime: null,
    remark: null,
    params: {},
    menuId: 3,
    menuName: '系统工具',
    parentName: null,
    parentId: 0,
    orderNum: 3,
    path: 'tool',
    component: null,
    query: '',
    isFrame: '1',
    isCache: '0',
    menuType: 'M',
    visible: '0',
    status: '0',
    perms: '',
    icon: 'tool',
    children: []
  }
]
